version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade pip wheel awscli . -r requirements.txt
      # setup git-secrets
      - WD=$(pwd)
      - cd /tmp
      - git clone https://github.com/awslabs/git-secrets.git
      - cd git-secrets
      - make install
      - cd ${WD}
  build:
    commands:
      - pre-commit run --all-files
